name: Build AUR Packages

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'  #Runs every Sunday at midnight

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Arch Linux Docker Container & Setup Environment
        run: |
          sudo apt-get update && sudo apt-get upgrade -y 
          sudo apt-get remove -y containerd containerd.io
          sudo apt-get install -y docker.io curl wget  
          sudo systemctl start docker 
          sudo usermod -aG docker $USER 
          docker pull archlinux:latest

      - name: Build Packages & Move them to Another directory
        run: |
          docker run --name arch archlinux:latest /bin/bash -c "
          pacman -Syu --noconfirm base-devel tree sudo git curl openh264 wget
          useradd -m builder && 
          echo 'builder ALL=(ALL) NOPASSWD: ALL ' >> /etc/sudoers 
          su - builder -c '
          cd /home/builder 
          git clone https://github.com/xeroxero8x/repo-builder
          mv repo-builder/* ./  
          bash ./scripts/build_packages.sh
          tree
          ' "
          source scripts/variables.sh 
          docker start arch
          docker cp arch:/home/builder/$TEMP_DIR ${GITHUB_WORKSPACE}/
          tree 
      - name: Upload Built Packages
        uses: actions/upload-artifact@v4
        with:
          name: aur-packages
          path: ${GITHUB_WORKSPACE}/pkgs/*.zst

      - name: Clean up
        run: docker rm -f arch

  move_push:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Built Packages
        uses: actions/download-artifact@v4
        with:
          name: aur-packages

      - name: Checkout Repository 
        uses: actions/checkout@v4

      - name: Setup Repo, Update Database and Push to Gitlab
        run: |
          source ./scripts/variables.sh 
          git clone https://$GIT_USERNAME:${{secrets.PAT}}@$REPO_URL $REPO_DIR        
          mv *.zst $REPO_DIR/$ARCH/ 
          cd $REPO_DIR
          bash ./scripts/update_database.sh
          bash ./scripts/push_repo.sh 
