name: Build AUR Packages

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'  #Runs every Sunday at midnight

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Arch Linux Docker Container & Setup Environment
        run: |
          sudo apt-get update && sudo apt-get upgrade -y 
          sudo apt-get remove -y containerd containerd.io
          sudo apt-get install -y docker.io curl wget  
          sudo systemctl start docker 
          sudo usermod -aG docker $USER 
          docker pull archlinux:latest

      - name: Build Packages & Push to remote repo
        env: 
          PAT: ${{ secrets.PAT }}
        run: |
          docker run --name arch archlinux:latest /bin/bash -c "
          pacman -Syu --noconfirm base-devel tree sudo git curl openh264 wget pacman-contrib
          useradd -m builder && 
          echo 'builder ALL=(ALL) NOPASSWD: ALL ' >> /etc/sudoers 
          su - builder -c ' 
          git clone https://github.com/xeroxero8x/repo-builder
          mv repo-builder/* ./  
          source ./scripts/variables.sh 
          bash ./scripts/build_packages.sh
          bash ./scripts/update_database.sh
          bash ./scripts/push_repo.sh 
          ' "
