name: Build AUR Packages

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'  #Runs every Sunday at midnight

jobs:
  build:
    runs-on: ubuntu-latest
    container:
        image: archlinux:latest
        env: 
          PAT: ${{secrets.PAT}} #Personal access token if your repo is on github or project access token if it's on gitlab 
          GIT_EMAIL: ${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com
          GIT_USERNAME: ${{ github.actor }}
          REPO_DIR: "aur-prebuilt" #repo name 
          ARCH: "x86_64" #Architecture of your device 
          PACKAGE_LIST: "include.list" #Name of the packages list 
          USER: "builder" #Non root user 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Concatenate values to Environment
        run: |
          echo "REPO_URL=gitlab.com/$GIT_USERNAME/$REPO_DIR" >> $GITHUB_ENV
          echo "DB_FILE=$REPO_DIR.db" >> $GITHUB_ENV
          echo "FILES_FILE=$REPO_DIR.files" >> $GITHUB_ENV
          echo "XXXX=/home/$USER" >> $GITHUB_ENV #You might think it's something bad but I am unable think of a name for it open an issue if you can find a good name that matches it's use.
      - name: Setup Environment 
        run: |
          set -e 
          echo "$USER"
          pacman -Syu --noconfirm sudo 
          useradd -m $USER && echo "$USER ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          su - $USER
          sudo chown -R $USER:$USER /home/$USER
          cd /home/$USER 
          sudo pacman -Syu --noconfirm git base-devel curl wget openh264 vifm pacman-contrib archlinux-keyring bat
          sudo -u $USER git clone https://aur.archlinux.org/yay.git
          ls -la
          cd yay
          sudo -u $USER makepkg -si --noconfirm
          cd .. && rm -rf yay 
          sudo -u $USER git clone https://$REPO_URL $REPO_DIR
          sudo -u $USER rm -rf $REPO_DIR/$ARCH/*.zst
 
      - name: Build Packages 
        run: |
          su - $USER
          ./scripts/build_packages.sh

      - name: Update Database
        run: |
          su - $USER
          ./scripts/update_database.sh
        
      - name: Push to repo
        run: |
          su - $USER
          ./scripts/push_repo.sh
          