name: Build AUR Packages

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'  #Runs every Sunday at midnight

jobs:
  build:
    runs-on: ubuntu-latest
    container:
        image: archlinux:latest
        env: 
          PAT: ${{secrets.PAT}}
          GIT_EMAIL: ${{secrets.EMAIL}}
          GIT_USERNAME: "xeroxero8x"
          REPO_DIR: "aur-prebuilt"
          ARCH: "x86_64"
          AUR_DIR: "aur-packages"
          PACKAGE_LIST: "include.list"
          USER: "builder"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Concatenate values to Environment
        run: |
          echo "REPO_URL=gitlab.com/$GIT_USERNAME/$REPO_DIR" >> $GITHUB_ENV
          echo "DB_FILE=$REPO_DIR.db" >> $GITHUB_ENV
          echo "FILES_FILE=$REPO_DIR.files" >> $GITHUB_ENV
          echo "XXXX=/home/$USER" >> $GITHUB_ENV
      - name: Setup Environment 
        run: |
          set -e 
          pacman -Syu --noconfirm sudo 
          useradd -m builder && echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          sudo --login --user=builder 
          sudo chown -R builder:builder /home/builder
          cd /home/builder
          sudo pacman -Syu --noconfirm git base-devel curl wget openh264 vifm pacman-contrib archlinux-keyring bat
          sudo -u builder git clone https://aur.archlinux.org/yay.git &&  \
          sudo chown -R builder:builder /home/builder 
          cd yay && \
          sudo -u builder makepkg -si --noconfirm
          cd .. && rm -rf yay 
          sudo -u builder git clone https://$REPO_URL $REPO_DIR
 
      - name: Build Packages 
        run: |
          su - builder
          ./scripts/build_packages.sh

      - name: Update Database
        run: |
          su - builder
          ./scripts/update_database.sh
        
      - name: Push to repo
        run: |
          su - builder
          ./scripts/push_repo.sh
