name: Build AUR Packages

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'  #Runs every Sunday at midnight

jobs:
  build_docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository 
        uses: actions/checkout@v4
      - name: Build and Push docker image 
        uses: docker/build-push-action@v6
        env:
          GIT_USERNAME: xeroxero8x
          REPO: repo-builder
        with:
          push: true
          tags: $GIT_USERNAME/$REPO:latest 
  build_pkgs:
    runs-on: ubuntu-latest
    container:
        image: ghcr.io/xeroxero8x/repo-builder:latest
        env: 
          PAT: ${{secrets.PAT}}
          GIT_EMAIL: ${{secrets.EMAIL}}
          GIT_USERNAME: xeroxero8x
          REPO_DIR: aur-prebuilt
          ARCH: x86_64
          REPO_URL: gitlab.com/$GIT_USERNAME/$REPO_DIR
          AUR_DIR: aur-packages
          DB_FILE: $REPO_DIR.db
          FILES_FILE: $REPO_DIR.files
          PACKAGE_LIST: include.list 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Environment 
        run: |
          sudo pacman -Syu --noconfirm git base-devel curl wget openh264

      - name: Build Packages 
        run: | 
          bash ./scripts/build_packages.sh

      - name: Update Database
        run: |
          bash ./scripts/update_database.sh
        
      - name: Push to repo
        run: |
          bash ./scripts/push_repo.sh
