name: Build AUR Packages

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'  #Runs every Sunday at midnight

jobs:
  build:
    runs-on: ubuntu-latest
    container:
        image: archlinux:latest
        env: 
          PAT: ${{secrets.PAT}}
          GIT_EMAIL: ${{secrets.EMAIL}}
          GIT_USERNAME: xeroxero8x
          REPO_DIR: aur-prebuilt
          ARCH: x86_64
          REPO_URL: gitlab.com/$GIT_USERNAME/$REPO_DIR
          AUR_DIR: aur-packages
          DB_FILE: $REPO_DIR.db
          FILES_FILE: $REPO_DIR.files
          PACKAGE_LIST: include.list 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Environment 
        run: |
          set -e
          pacman -Syu --noconfirm sudo 
          useradd -m builder && echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          sudo --login --user=builder 
          sudo chown -R builder:builder /home/builder
          cd /home/builder
          sudo pacman -Syu --noconfirm git base-devel curl wget openh264 vifm pacman-contrib archlinux-keyring bat
          sudo -u builder git clone https://aur.archlinux.org/aurutils.git && ls -la && \
          cd aurutils && \
          makepkg -si --noconfirm
          ls -la 
          cd .. && rm -rf aurutils
          sudo -u builder git clone https://$REPO_URL $REPO_DIR
          echo -e "[$REPO_DIR]\nSigLevel = Optional TrustAll\nServer = file:///$HOME/$REPO_DIR/$ARCH/" | sudo tee -a /etc/pacman.conf
          bat /etc/pacman.conf 
          echo "$USER"
      - name: Build Packages 
        run: | 
          sudo -u builder bash ./scripts/build_packages.sh

      - name: Update Database
        run: |
          sudo -u builder bash ./scripts/update_database.sh
        
      - name: Push to repo
        run: |
          sudo -u builder bash ./scripts/push_repo.sh
